name: release

on:
  pull_request:
    types: [ labeled ]
    branches:
      - master

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current version
        shell: bash
        run: |
          CURRENT_VERSION=$(awk '/^version = / { gsub("\"", ""); print $3 }' build.gradle)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: pusher/public_actions
          path: .github/actions
      - uses: ./.github/actions/prepare-version-bump
        id: bump
        with:
          current_version: ${{ env.CURRENT_VERSION }}
      - name: Push
        shell: bash
        run: |
          perl -pi -e 's/version = "${{env.CURRENT_VERSION}}"/version = "${{steps.bump.outputs.new_version}}"/' build.gradle
          perl -pi -e 's/${{env.CURRENT_VERSION}}/${{steps.bump.outputs.new_version}}/' README.md

          git add build.gradle README.md CHANGELOG.md
          git commit -m "Bump to version ${{ steps.bump.outputs.new_version }}"
          git push
